[package]
name = "bors"
version = "0.0.0"
authors = ["Jack Moffitt <metajack@fb.com>", "Brandon Williams <bmwill@fb.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
thiserror = "1.0.5"
hyper = { version = "=0.13.0-alpha.4", features = ["unstable-stream"] }
tokio = "=0.2.0-alpha.6"
futures = { version = "=0.3.0-alpha.19", package = "futures-preview" }
graphql_client = "0.8.0"
